name: rptools
channels:
  - conda-forge
dependencies:
  - python <=3.11
  - brs_utils # rpcompletion, rpfba, Args
  - cobra # rpfba, rpextractsink, rplibs
  - timeout-decorator # rpextractsink
  - rdkit # rpextractsink, rplibs
  - python-libsbml # rplibs, rpfba
  - numpy # rplibs, rpfba, rpscore, rpthermo
  - pandas # rplibs, rpthermo
  - scipy # rpthermo
  - equilibrator-api # rpthermo
  - equilibrator-cache >=0.5.4 # rpthermo
  - colored # rplibs
  - networkx >=2.5 # rplibs
  - filetype  # rplibs (conda-forge)
  - rr_cache >=3.1.1 # rpcompletion
  - rxn_rebuild # rpcompletion
  - chemlite # rpcompletion ,rpfba, rpthermo
  - h5py # rpscore
  - xgboost # rpscore
  - bs4 # rpviz
