name: rptools
channels:
  - conda-forge
dependencies:
  - python <=3.10
  - brs_utils # rpcompletion, rpfba, Args
  - cobra >=0.26.3 # rpfba, rpextractsink, rplibs
  - timeout-decorator # rpextractsink
  - rdkit # rpextractsink, rplibs, rpcompletion
  - python-libsbml # rplibs, rpfba
  - numpy <1.25 # rplibs, rpfba, rpscore, rpthermo ('np.find_common_type' deprecated)
  - pandas <2.0 # rplibs, rpthermo ('frame.append' deprecated)
  - scipy # rpthermo
  - equilibrator-api # rpthermo
  - equilibrator-cache >=0.5.4 # rpthermo
  - colored # rplibs
  - networkx >=2.5 # rplibs
  - filetype  # rplibs (conda-forge)
  - rr_cache >=3.2.0 # rpcompletion
  - rxn_rebuild >=3.1.3 # rpcompletion
  - chemlite # rpcompletion ,rpfba, rpthermo
  - h5py # rpscore
  - xgboost # rpscore
  - bs4 # rpviz
